### ISSUE TITLE
Add more info and link laravel repo

### ISSUE THREAD

**Issue by lukasoppermann** [stevenmaguire/middleware-csp-php#1]
Hey,

I think you should add more info on the usage of this package and also on the options available and what it means, so people can get started right from your package without reading up about it somewhere else.

You could add all needed info here and link here from the laravel repo, so users of the laravel version get the information as well.

**Comment by stevenmaguire** [comment]
@lukasoppermann that's an awesome idea! What kind of information do you think is missing? Could you submit a PR with an outline in an updated README and we can work together to edit?

**Comment by lukasoppermann** [comment]
@stevenmaguire sure thing, I will work on it tomorrow.

**Comment by stevenmaguire** [comment]
@lukasoppermann I've merged your PR (thank you!) and added a bit more detail. Please take a look and submit a PR if there are changes you think would help improve consumption of this project.

**Comment by lukasoppermann** [comment]
Hey @stevenmaguire you additions are perfect, currently I have nothing to add. However I feel this now gives people who are new to the topic a very good start. 👍
