### ISSUE TITLE
Add loosely related headers

### ISSUE THREAD

**Issue by lukasoppermann** [stevenmaguire/middleware-csp-php#3]
Hey @stevenmaguire,

I know the package is called middleware-**csp**-php, but anyway: what do you think about adding 
- `HTTP Strict Transport Security`
- `X-Content-Type-Options`
- `X-Frame-Options`
- `X-XSS-Protection`

More info can be found at https://wiki.mozilla.org/Security/Guidelines/Web_Security#HTTP_Strict_Transport_Security.

I think those headers a pretty closely related, as they are all dealing with security, avoiding XSS and similar attacks, what do you think?

**Comment by stevenmaguire** [comment]
I like the idea. Are there any other packages out there that provide this support? I don't feel like it is a 100% fit for this project and if there is no other support out there I think it's reasonable to include here. 

I would want to ensure that each of the enforcement concepts are isolated such that they do not become tightly coupled. For instance, we currently have configuration like: 

``` php
return [
    'content' => [
        'default' => 'global',
        'profiles' => [
            //
        ]
    ]
];
```

I would expect something like:

``` php
return [
    'content' => [
        'default' => 'global',
        'profiles' => [
            //
        ]
    ],
    'http-strict-transport' => [
        //
    ],
    'content-type' => [
        //
    ],
    'x-frame-options' => [
        //
    ],
    'xss' => [
        //
    ],
];
```

Then within the middleware itself, the implementations would be applied in isolation:

``` php
    public function handle(ResponseInterface $response, $profiles = [])
    {
        array_map(function ($profile) {
            $this->loadProfileByKey($profile);
        }, $profiles);

        $response = $this->addPolicyHeader($response);
        $response = $this->addHttpStrictTransportHeader($response);
        $response = $this->addContentTypeHeader($response);
        $response = $this->addXFrameOptionsHeader($response);
        $response = $this->addXssProtectionHeader($response);

        return $response;
    }
```

This would offer some flexibility to implement these header manipulations within one middleware or separately. 

My concern with coupling them is that if a strong case is made to move to a different package or split out, I don't want to refactor a bunch. There is a way for this package to house several independent response header modification "modules". I don't know what it looks like yet and I am open to exploring :)

**Comment by lukasoppermann** [comment]
Hey @stevenmaguire I did not find a project that just provides those headers. I understand your feeling that it is not a 100% fit. However I would argue that it is pretty close:
- they are all security related headers
- they deal with xss and closely related types of attacks
- people who are implementing csp are pretty likely to also implement those headers

People are free to omit those headers and it should not be a big overhead for the package right?

That being set I like your idea of implementing it in a flexible way. 👍
