### ISSUE TITLE
Add CSP Nonce & Hash

### ISSUE THREAD

**Issue by lukasoppermann** [stevenmaguire/middleware-csp-php#4]
Hey @stevenmaguire,

so the problem with a CSP is always inline scripts, like google analytics. There are two solution:
- csp nonce 
- csp hash

Read more about it here: https://blog.mozilla.org/security/2014/10/04/csp-for-the-web-we-have/

I think this should be somehow integrated into this package, so that as a package user I don't really have to worry about it. What do you think?

My first idea would be to add some helper methods. `csp_nonce` and `csp_hash`. The `csp_nonce` is pretty simple, I added a rough draft below (this would of course need to be done in a cleaner way). 

``` php
function csp_none(){
    $nonce = hash('sha256',time().uniqid(rand(), true));

    foreach(config('security.content.profiles') as $name => $profile){

        if( isset($profile['script-src']) ){
            config([
                "security.content.profiles.$name.script-src" => array_merge(
                    (array)$profile['script-src'],
                    ["'nonce-".$nonce."'"]
                )
            ]);
        }

    }

    return "nonce=".$nonce;
}
```

The complexity comes from the possibility of having multiple policies defined and of course the lack of knowledge if the `script-src` is an `array` or a `string`.

The `csp_hash` function would actually need to get the script as an argument, so it can calculate a hash.

However this helper was done for Laravel. Maybe you want to add more ways to interact with the csp via code, methods like `add_csp('script-src', ['array','of','csps'], $profile or '*' for all)` would make this a bit easier.

**Comment by stevenmaguire** [comment]
I fully endorse helping to remove obstacles from the developer's path. I am having a hard time visualizing the problem and solution here. Leaving the actual code within this project aside for the moment, what exactly do you envision happening when the ResponseInterface is updated to include CSP?

**Comment by lukasoppermann** [comment]
Hey @stevenmaguire, I am not 100% sure I understand you question.

The problem is basically this: If you do not want to use `unsafe-inline`, which is not really recommended, as it is like using a sledgehammer to put up a picture frame, you need to either use a `hash` or `nonce`. This allows adding a csp for one specific piece of inline code, rather than allowing all inline code.

However, for both procedures a value, either the nonce or the hash, needs to be added to the csp and returned within the csp header.

With a `nonce` a string of `"'nonce-12adfs1123'"` needs to be added to the csp and this nonce needs to be added into the script tag itself `<script nonce="12adfs1123">`. The nonce needs to be changed on every page load, otherwise it would defeat the purpose, as it must not be guessable.

With the `hash` the script tag does not need to be adjusted, however a hash needs to be calculated from the script content itself. E.g. a hash of `alert('hello')`. This hash needs to be sent via the csp header like so: `'sha256-234kjdskfaj32l14l243lmo9jadfs231'`. The has needs technically only be calculated once, as long as the script does not change. The browser will calculate a hash from the script code and compare both hashes. (I think this method is not very well supported so far, but hopefully will be soon).

Does this answer your question? Or did I miss the point? 😄
